<?php

class Years {
    const DEFAULT_YEAR = false;

    /**
     * @return int[]
     */
    public static function slugsAndYears() {
        return array (
            '50states' => 2003,
            'a-outline-none' => 2001,
            'additive-font-size' => 2001,
            'ancient-tidy-tutorial' => 1999,
            'anti-cache' => 2001,
            'asp' => 2001,
            'asp-selectbox-function' => 2016,
            'autocalc' => 2002,
            'bluedragon-net-installer' => 2010,
            'border-style' => 2002,
            'call-original-version-of-redefined-vbscript' => 2016,
            'camel-selector' => 2002,
            'checkbox-validate' => 2001,
            'clock-concept' => 2024,
            'coldfusion-break-db' => 2003,
            'coldfusion-force-download' => 2016,
            'coldfusion-titlecase' => 2003,
            'compare-fields' => 2002,
            'connect-to-remote-server' => 2004,
            'copy-to-clipboard-javascript' => 2005,
            'countdown' => 2005,
            'countdown-daily-to-a-time' => 2011,
            'countdown-to-the-first' => 2011,
            'crossdomain' => 2009,
            'css3-smiley' => 2024,
            'detection-real' => 1999,
            'domain-name-sql-excel' => 2016,
            'dropdown-focus' => 2001,
            'dropdown-only-some-new-window' => 2002,
            'email-submission-stinks' => 2003,
            'first-child-last-child' => 2011,
            'gallery' => 2001,
            'gettysburg' => 2006,
            'goal50' => 2024,
            'group-concat-mysql' => 2016,
            'image-border' => 1999,
            'image-hover' => 2004,
            'input-direction' => 2006,
            'interesting-date-layout' => 1999,
            'invisible-unspiderable-link' => 2024,
            'is-email' => 2009,
            'java-tags' => 1999,
            'keycode' => 2011,
            'larger-checkbox-with-css' => 2009,
            'make-unique-id' => 2005,
            'mathml' => 2024,
            'meaningful-html-class-names' => 2024,
            'media' => 2024,
            'misc-files' => 2016,
            'mm_validateform' => 2009,
            'modify-the-box' => 2001,
            'mouseover-vote' => 1999,
            'mouseover-vote100' => 1999,
            'museum' => 2010,
            'my-first-vbscript-class' => 2016,
            'not-valid-itunes-library' => 2004,
            'oncontextmenu' => 2005,
            'onunload-window-open-evil' => 2001,
            'outbound-link-confirmation' => 2013,
            'password-maker' => 2009,
            'php-all-websafe' => 2010,
            'php-php3-mod-rewrite' => 2001,
            'pinkvalidation' => 2002,
            'plus-plus-a-string-php' => 2024,
            'quick-jquery-overlay' => 2018,
            'quote-to-dl' => 2024,
            'random-string-in-sql' => 2000,
            'response-end-is-like-exit-in-php' => 2016,
            'robots-nocontent' => 2008,
            'rounded-mozilla' => 2024,
            't-paamayim-nekudotayim' => 2016,
            'the-problem-with-blur' => 2001,
            'undocumented-linklint' => 2002,
            'unix-batch-file-rename' => 2004,
            'url-compare' => 2024,
            'urlencode' => 2001,
            'user-preference-for-new-windows' => 2004,
            'vaguely-interesting-layout' => 2010,
            'validate-checkbox' => 2001,
            'validate-image' => 2002,
            'vbscript-always-elseif-never-else-if' => 2016,
            'w3c-with-and-without-css' => 2002,
            'windows-export-file-list' => 2000,
            'ws-ftp-password-decoder' => 2001,
            'xml-encode' => 2009,
            'single-pixel-gif' => 2011,

                'asp-cdonts' => 2005,
                'bug-mac-netscape-forms-update' => 1998,
                'change-space-between-paragraphs' => 2006,
                'format-time' => 2002,
                'rtf' => 2024,
//
        );
    }
}