<?php
require_once('../../loader.php');
$lab = new Lab();
$lab->printHeader('Gettysburg Address in HTML Buttons!');

?>
    <p class="date-attribution">Created in February 2006. For no good reason.</p>
<h1>Gettysburg Address in HTML Buttons!</h1>


<form action="../" style="max-width: 500px">
<input type="button" name="button1" value="Four">
<input type="button" name="button2" value="score">
<input type="button" name="button3" value="and">
<input type="button" name="button4" value="seven">
<input type="button" name="button5" value="years">
<input type="button" name="button6" value="ago">
<input type="button" name="button7" value="our">
<input type="button" name="button8" value="fathers">
<input type="button" name="button9" value="brought">
<input type="button" name="button10" value="forth">
<input type="button" name="button11" value="on">
<input type="button" name="button12" value="this">
<input type="button" name="button13" value="continent">
<input type="button" name="button14" value="a">
<input type="button" name="button15" value="new">
<input type="button" name="button16" value="nation,">
<input type="button" name="button17" value="conceived">
<input type="button" name="button18" value="in">
<input type="button" name="button19" value="liberty">
<input type="button" name="button20" value="and">
<input type="button" name="button21" value="dedicated">
<input type="button" name="button22" value="to">
<input type="button" name="button23" value="the">
<input type="button" name="button24" value="proposition">
<input type="button" name="button25" value="that">
<input type="button" name="button26" value="all">
<input type="button" name="button27" value="men">
<input type="button" name="button28" value="are">
<input type="button" name="button29" value="created">
<input type="button" name="button30" value="equal.">
<input type="button" name="button31" value="Now">
<input type="button" name="button32" value="we">
<input type="button" name="button33" value="are">
<input type="button" name="button34" value="engaged">
<input type="button" name="button35" value="in">
<input type="button" name="button36" value="a">
<input type="button" name="button37" value="great">
<input type="button" name="button38" value="civil">
<input type="button" name="button39" value="war,">
<input type="button" name="button40" value="testing">
<input type="button" name="button41" value="whether">
<input type="button" name="button42" value="that">
<input type="button" name="button43" value="nation">
<input type="button" name="button44" value="or">
<input type="button" name="button45" value="any">
<input type="button" name="button46" value="nation">
<input type="button" name="button47" value="so">
<input type="button" name="button48" value="conceived">
<input type="button" name="button49" value="and">
<input type="button" name="button50" value="so">
<input type="button" name="button51" value="dedicated">
<input type="button" name="button52" value="can">
<input type="button" name="button53" value="long">
<input type="button" name="button54" value="endure.">
<input type="button" name="button55" value="We">
<input type="button" name="button56" value="are">
<input type="button" name="button57" value="met">
<input type="button" name="button58" value="on">
<input type="button" name="button59" value="a">
<input type="button" name="button60" value="great">
<input type="button" name="button61" value="battlefield">
<input type="button" name="button62" value="of">
<input type="button" name="button63" value="that">
<input type="button" name="button64" value="war.">
<input type="button" name="button65" value="We">
<input type="button" name="button66" value="have">
<input type="button" name="button67" value="come">
<input type="button" name="button68" value="to">
<input type="button" name="button69" value="dedicate">
<input type="button" name="button70" value="a">
<input type="button" name="button71" value="portion">
<input type="button" name="button72" value="of">
<input type="button" name="button73" value="that">
<input type="button" name="button74" value="field">
<input type="button" name="button75" value="as">
<input type="button" name="button76" value="a">
<input type="button" name="button77" value="final">
<input type="button" name="button78" value="resting-place">
<input type="button" name="button79" value="for">
<input type="button" name="button80" value="those">
<input type="button" name="button81" value="who">
<input type="button" name="button82" value="here">
<input type="button" name="button83" value="gave">
<input type="button" name="button84" value="their">
<input type="button" name="button85" value="lives">
<input type="button" name="button86" value="that">
<input type="button" name="button87" value="that">
<input type="button" name="button88" value="nation">
<input type="button" name="button89" value="might">
<input type="button" name="button90" value="live.">
<input type="button" name="button91" value="It">
<input type="button" name="button92" value="is">
<input type="button" name="button93" value="altogether">
<input type="button" name="button94" value="fitting">
<input type="button" name="button95" value="and">
<input type="button" name="button96" value="proper">
<input type="button" name="button97" value="that">
<input type="button" name="button98" value="we">
<input type="button" name="button99" value="should">
<input type="button" name="button100" value="do">
<input type="button" name="button101" value="this.">
<input type="button" name="button102" value="But">
<input type="button" name="button103" value="in">
<input type="button" name="button104" value="a">
<input type="button" name="button105" value="larger">
<input type="button" name="button106" value="sense,">
<input type="button" name="button107" value="we">
<input type="button" name="button108" value="cannot">
<input type="button" name="button109" value="dedicate,">
<input type="button" name="button110" value="we">
<input type="button" name="button111" value="cannot">
<input type="button" name="button112" value="consecrate,">
<input type="button" name="button113" value="we">
<input type="button" name="button114" value="cannot">
<input type="button" name="button115" value="hallow">
<input type="button" name="button116" value="this">
<input type="button" name="button117" value="ground.">
<input type="button" name="button118" value="The">
<input type="button" name="button119" value="brave">
<input type="button" name="button120" value="men,">
<input type="button" name="button121" value="living">
<input type="button" name="button122" value="and">
<input type="button" name="button123" value="dead">
<input type="button" name="button124" value="who">
<input type="button" name="button125" value="struggled">
<input type="button" name="button126" value="here">
<input type="button" name="button127" value="have">
<input type="button" name="button128" value="consecrated">
<input type="button" name="button129" value="it">
<input type="button" name="button130" value="far">
<input type="button" name="button131" value="above">
<input type="button" name="button132" value="our">
<input type="button" name="button133" value="poor">
<input type="button" name="button134" value="power">
<input type="button" name="button135" value="to">
<input type="button" name="button136" value="add">
<input type="button" name="button137" value="or">
<input type="button" name="button138" value="detract.">
<input type="button" name="button139" value="The">
<input type="button" name="button140" value="world">
<input type="button" name="button141" value="will">
<input type="button" name="button142" value="little">
<input type="button" name="button143" value="note">
<input type="button" name="button144" value="nor">
<input type="button" name="button145" value="long">
<input type="button" name="button146" value="remember">
<input type="button" name="button147" value="what">
<input type="button" name="button148" value="we">
<input type="button" name="button149" value="say">
<input type="button" name="button150" value="here,">
<input type="button" name="button151" value="but">
<input type="button" name="button152" value="it">
<input type="button" name="button153" value="can">
<input type="button" name="button154" value="never">
<input type="button" name="button155" value="forget">
<input type="button" name="button156" value="what">
<input type="button" name="button157" value="they">
<input type="button" name="button158" value="did">
<input type="button" name="button159" value="here.">
<input type="button" name="button160" value="It">
<input type="button" name="button161" value="is">
<input type="button" name="button162" value="for">
<input type="button" name="button163" value="us">
<input type="button" name="button164" value="the">
<input type="button" name="button165" value="living">
<input type="button" name="button166" value="rather">
<input type="button" name="button167" value="to">
<input type="button" name="button168" value="be">
<input type="button" name="button169" value="dedicated">
<input type="button" name="button170" value="here">
<input type="button" name="button171" value="to">
<input type="button" name="button172" value="the">
<input type="button" name="button173" value="unfinished">
<input type="button" name="button174" value="work">
<input type="button" name="button175" value="which">
<input type="button" name="button176" value="they">
<input type="button" name="button177" value="who">
<input type="button" name="button178" value="fought">
<input type="button" name="button179" value="here">
<input type="button" name="button180" value="have">
<input type="button" name="button181" value="thus">
<input type="button" name="button182" value="far">
<input type="button" name="button183" value="so">
<input type="button" name="button184" value="nobly">
<input type="button" name="button185" value="advanced.">
<input type="button" name="button186" value="It">
<input type="button" name="button187" value="is">
<input type="button" name="button188" value="rather">
<input type="button" name="button189" value="for">
<input type="button" name="button190" value="us">
<input type="button" name="button191" value="to">
<input type="button" name="button192" value="be">
<input type="button" name="button193" value="here">
<input type="button" name="button194" value="dedicated">
<input type="button" name="button195" value="to">
<input type="button" name="button196" value="the">
<input type="button" name="button197" value="great">
<input type="button" name="button198" value="task">
<input type="button" name="button199" value="remaining">
<input type="button" name="button200" value="before">
<input type="button" name="button201" value="us--that">
<input type="button" name="button202" value="from">
<input type="button" name="button203" value="these">
<input type="button" name="button204" value="honored">
<input type="button" name="button205" value="dead">
<input type="button" name="button206" value="we">
<input type="button" name="button207" value="take">
<input type="button" name="button208" value="increased">
<input type="button" name="button209" value="devotion">
<input type="button" name="button210" value="to">
<input type="button" name="button211" value="that">
<input type="button" name="button212" value="cause">
<input type="button" name="button213" value="for">
<input type="button" name="button214" value="which">
<input type="button" name="button215" value="they">
<input type="button" name="button216" value="gave">
<input type="button" name="button217" value="the">
<input type="button" name="button218" value="last">
<input type="button" name="button219" value="full">
<input type="button" name="button220" value="measure">
<input type="button" name="button221" value="of">
<input type="button" name="button222" value="devotion--that">
<input type="button" name="button223" value="we">
<input type="button" name="button224" value="here">
<input type="button" name="button225" value="highly">
<input type="button" name="button226" value="resolve">
<input type="button" name="button227" value="that">
<input type="button" name="button228" value="these">
<input type="button" name="button229" value="dead">
<input type="button" name="button230" value="shall">
<input type="button" name="button231" value="not">
<input type="button" name="button232" value="have">
<input type="button" name="button233" value="died">
<input type="button" name="button234" value="in">
<input type="button" name="button235" value="vain,">
<input type="button" name="button236" value="that">
<input type="button" name="button237" value="this">
<input type="button" name="button238" value="nation">
<input type="button" name="button239" value="under">
<input type="button" name="button240" value="God">
<input type="button" name="button241" value="shall">
<input type="button" name="button242" value="have">
<input type="button" name="button243" value="a">
<input type="button" name="button244" value="new">
<input type="button" name="button245" value="birth">
<input type="button" name="button246" value="of">
<input type="button" name="button247" value="freedom,">
<input type="button" name="button248" value="and">
<input type="button" name="button249" value="that">
<input type="button" name="button250" value="government">
<input type="button" name="button251" value="of">
<input type="button" name="button252" value="the">
<input type="button" name="button253" value="people,">
<input type="button" name="button254" value="by">
<input type="button" name="button255" value="the">
<input type="button" name="button256" value="people,">
<input type="button" name="button257" value="for">
<input type="button" name="button258" value="the">
<input type="button" name="button259" value="people">
<input type="button" name="button260" value="shall">
<input type="button" name="button261" value="not">
<input type="button" name="button262" value="perish">
<input type="button" name="button263" value="from">
<input type="button" name="button264" value="the">
<input type="button" name="button265" value="earth.">
</form>

<?php
$lab->printFooter([
	'comments' => true
]);
